### ISSUE TITLE
Notice: Undefined variable: PROJECT

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1706]
I see this notice on most BOINC project websites. Please fix it.
```
Notice: Undefined variable: PROJECT in /[SomePath]/html/languages/compiled/pl.po.inc on line 956
```

**Comment by ChristianBeer** [comment]
Can you post some concrete projects where this is happening? I guess this is only happening if you chose Polish as language? What we can do is find out if we can fix the root cause but then the projects where you see this probably need to pull in the new translations or a fix.

**Comment by JuhaSointusalo** [comment]
It's coming from [locale/pl/BOINC-Project-Generic.po](https://github.com/BOINC/boinc/blob/master/locale/pl/BOINC-Project-Generic.po#L5022) and/or [html/languages/translations/pl.po](https://github.com/BOINC/boinc/blob/master/html/languages/translations/pl.po#L5022).

Somehow I thought this was already fixed but doesn't look like it. I think it doesn't need more work than replacing $PROJECT with %1 . Google Translate turns the English version into similar text as the Polish is now.

**Comment by ChristianBeer** [comment]
Found it. I fixed the Polish translation on transifex. But this will only update on github as soon as someone completes the Polish translation there. And someone has to fix the txgh bridge that transfers completed translations from transifex to github. This seems to be broken at the moment.

**Comment by ChristianBeer** [comment]
I imported the updated Polish translation (among others), this should be fixed now.

**Comment by sirzooro** [comment]
Thanks. BTW, boinc.berkeley.edu also started showing this after recent layout update.

**Comment by ChristianBeer** [comment]
It seems that boinc.berkeley.edu needs a recompile of translation files. As I'm going to update the translation templates soon (because a lot of wording changed) this will then hopefully be fixed when new translations are coming back from transifex.

**Comment by davidpanderson** [comment]
I ran update_translations.php for the BOINC web site.

**Comment by sirzooro** [comment]
I still see it. I tried to open forum and my profile pages (they should not be cached) and warning is there too.

**Comment by ChristianBeer** [comment]
The problem with the polish translation is that it is not 100% translated so it is not updated in github and not updated in the projects. So if you want this fixed you need to translate at least the BOINC-Web.pot resource to 100% so I can update the repository with it.
