### ISSUE TITLE
Administrative installation adds inappropriate registry entries

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#824]
**Reported by Richard Haselgrove on 19 Jun 39144534 20:26 UTC**
Running the installer with the '/a' (administrative installation) switch should not make changes to the local sysem registry.

Testing with both v6.4.5 and v6.6.10, I found that both INSTALLDIR and DATADIR were set to point to the network server image directory - this would break any running BOINC v6 on the workstation used for network upload. Fortunately I was running BOINC v5.

However, the administrative installer does not read back either registry key for subsequent installations - it defaults to the root of the first available mapped network drive.

An administrative installation should either make no local registry changes at all, or maintain and use its own ADMININSTALLDIR key.

Also, the final screen (attached) on the test machine (Windows XP SP3, workgroup) is contradictory - if the installation was successful (as it appears to have been), why am I being directed to run a repair tool from add/remove programs?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/847

**Comment by romw** [comment]
**Commented by Nicolas on 20 Feb 39150510 07:06 UTC**
"InstallShield wizard" is an implementation detail, internal and technical information the user doesn't care about. "BOINC installation" finished, not "InstallShield wizard".

**Comment by romw** [comment]
**Commented by romw on 27 Oct 39159104 19:33 UTC**
Punting setup bugs to 6.10.

**Comment by romw** [comment]
**Commented by Richard Haselgrove on 5 May 39169958 11:33 UTC**
Following an enquiry about admin setups at SETI, I tested the v6.2.19 installer: yes, it modifies the local registry too. Just warning people in case they decide not to wait until v6.10.x before trying their next admin setup.

**Comment by romw** [comment]
**Commented by ChristianB on 27 Jan 40704897 14:13 UTC**
Is this fixed in 6.10? Please reopen when not.

**Comment by romw** [comment]
**Commented by Richard Haselgrove on 17 Oct 40704973 10:13 UTC**
Tested both 6.10.58 and 6.11.7 under Windows XP. Problem remains as originally described. Reopening ticket.

**Comment by romw** [comment]
**Commented by romw on 3 Jun 40859072 11:33 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by romw** [comment]
**Commented by Richard Haselgrove on 23 Nov 43314006 18:30 UTC**
Behaviour remains the same in v7.0.64

**Comment by ChristianBeer** [comment]
I guess this is still a problem with current 7.6.33. Moving to 8.0 Milestone as this is most likely fixed when moving away from InstallShield.

**Comment by Ageless93** [comment]
Will we ever move away from InstallShield?

**Comment by RichardHaselgrove** [comment]
Retested with v7.8.3, at Jord's request. Couldn't deploy to a remote drive because of network configuration changes here (I don't have a dedicated server any more), but the registry corruption still occurs as before.
[BOINC RH Admin install.txt](https://github.com/BOINC/boinc/files/1411777/BOINC.RH.Admin.install.txt)

**Comment by truboxl** [comment]
While searching Google, I come across this [Superuser thread](https://superuser.com/questions/171917/force-a-program-to-run-without-administrator-privileges-or-uac)

Should be helpful to others who want to extract BOINC for network or portable install without tampering registries and admin rights

`cmd /min /C "set __COMPAT_LAYER=RUNASINVOKER && start "" boinc_7.8.3_windows_x86_64.exe /V /a"`

**Comment by RichardHaselgrove** [comment]
Thanks for that - tested and works as advertised. I've added it to the user manual at http://boinc.berkeley.edu/wiki/Creating_custom_installers
